name: Build and Test Workflow

on:
  push:
    branches:
      - devtask/*
  workflow_dispatch:
    inputs:
      release_version:
        description:  Provide the branch/tag to build and test
        required: false

jobs:

  build_test:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.release_version != '' }}

    steps:
    
      - name: Check out code
        uses: actions/checkout@v4.1.7
        with:
          ref: ${{  github.event.inputs.release_version }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Configure .npmrc for JFrog
        run: |
            echo "registry=https://${{ secrets.JFROG_HOST_NAME }}/artifactory/api/npm/${{ secrets.NPM_GOS_ALL_ARTIFACTORY }}/" > ~/.npmrc
            echo "//${{ secrets.JFROG_HOST_NAME }}/artifactory/api/npm/${{ secrets.NPM_GOS_ALL_ARTIFACTORY }}/:_authToken=${{ secrets.CUSTOMER_ZERO_TOKEN }}" >> ~/.npmrc
            echo "always-auth=true" >> ~/.npmrc

      - name: Install dependencies for Node
        run: npm install
           
      - name: Run tests
        run: npm test

